name: "customCNN"
cnn:
  conv_1: 16
  conv_2: 64
  conv_3: 128 
  kernel_1: 5
  kernel_2: 3
  kernel_3: 3
  stride_1: 1
  stride_2: 1
  stride_3: 2
  dropout_1: 0.3
  dropout_2: 0.4
  dropout_3: 0.5
  padding1: "valid"
  padding2: "valid" 
  padding3: "same"
  l2: 0.01
  pool_size: 2 
  pool_strides: 2 
  
dense:
  dense_1: 256
  dense_2: 128
  activation: sigmoid #for binary classification 