
#General settings for dataloder
dataset:
  dir_path: "/Users/annushka/Desktop/Melanoma_CLassifier/Melamoma_Classifier/datasets/preprocessed_images/" #dir where train/test folders are located
  csv_train: "/Users/annushka/Desktop/Melanoma_CLassifier/Melanoma_all_models/Melamoma_Classifier/datasets/ISIC_2020_Training_GroundTruth.csv"
  csv_test: "/Users/annushka/Desktop/Melanoma_CLassifier/Melanoma_all_models/Melamoma_Classifier/datasets/ISIC_2020_Test_Metadata.csv"
  batch_size: 32
  img_size: 260
  train_val_split: 0.8
  model_name: "effnetb2"
  num_classes: 1 #aka 0 or 1 


#Training params:
params:
  lr: 0.0004
  epochs: 20 
  lr_shedule: "cosine"
  label_smoothing: 0.1

finetune:
  lr:
  epochs: 20
  num_layers: 10
  lr_shefule: "cosine"
  label_smoothing: 0.1
  
model_params:
  dense:
    activation: sigmoid #for binary classification 
    dropout: 0.5

callbacks:
  monitor: "val_loss"
  min_lr: 0.0000001