#Training parameters 
lr: 0.0001
optimiser: adam #there is adamw for the ViT
epochs: 25
lr_shedule: "cosine"
label_smoothing: 0.0
restore_best_weights: False #thisa is because I changed to save_all_epochs
gamma: 3
